### ISSUE TITLE
Overrides applied to root project fails

### ISSUE THREAD

**Issue by stealthcode** [nebula-plugins/gradle-override-plugin#10]
When running a task on a sub-project only, the override plugin attempts to apply the override to the root project and if it cannot find the project property on the root then it fails. This happens when you apply a plugin to a sub project and that adds a property to the project but you don't apply that same plugin to the root project. I would expect that the override should either match the root or the sub project in this case, but would not be required to match the root if no property is found.

**Comment by bmuschko** [comment]
Seems like we only implemented this in the gradle-2.x branch. Thanks for backporting @rspieldenner.
