### ISSUE TITLE
"nebula.override" plugin is not available at plugins.gradle.org

### ISSUE THREAD

**Issue by mnasyrov** [nebula-plugins/gradle-override-plugin#13]
The plugin is not available at plugins.gradle.com, so it can not be applied by a following snippet.
```
plugins {
  id 'nebula.override' version '3.0.1'
}
```

ps. Thank you for this useful plugin!

**Comment by rspieldenner** [comment]
Ok will republish and check to see it is there

**Comment by rspieldenner** [comment]
Done
