### ISSUE TITLE
Subproject specific overrides

### ISSUE THREAD

**Issue by iwarapter** [nebula-plugins/gradle-override-plugin#14]
Can this plugin handle overrides for a specific subproject, e.g:

```
root
 --sub1
 --sub2
```

Is it possible to override a specific submodule property, e.g:

```
-Doverride.sub1.example.myProp=newValue
```

**Comment by rspieldenner** [comment]
I do not know. Would need to test it out.

**Comment by jmcgarr** [comment]
Closing out.
